### ISSUE TITLE
parts and tools Identifiers

### ISSUE THREAD

**Issue by jmwright** [Mach30/sliderule#10]
@m30-jrs We're now contemplating command lines like the following with sliderule-cli: `sr create parts.wss "Infineon TLSxxx"`. What would the `parts.wss` snippet be called? It's not a path, it's more of an abstract representation. It `parts` a class and `wss` is a subclass?

**Comment by m30-jrs** [comment]
Good question @jmwright. Over in the DOF architecture docs, I call them “listings/lists” (the data structure is technically a dictionary) of parts and tools. See https://github.com/Mach30/dof/blob/master/dist/DOF.adoc#component

Those lists are, for now, made up of component list items (not the most original name, I know).  See https://github.com/Mach30/dof/blob/master/dist/DOF.adoc#component-list-item

So, per current DOF docs, `parts.wss` would reference the `wss` item (or maybe entry) in the `parts` list.  I am open to discussing alternate terminology. All of this was decided quickly to just get the concepts captured when I was doing the initial modeling of the tres-wssm component.

**Comment by jmwright** [comment]
I don't have any better ideas on terminology, so I'm going to close this issue for now. We can reopen the discussion later, if needed.
